name: Deploy Code on EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          echo "Cloning Repository"
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST \
            "cd trading-assistant-backend && sudo git pull"
          echo "Install dependencies"
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST \
            "sudo -i bash -c 'cd /home/ubuntu/trading-assistant-backend && pnpm install'"
          echo "Start PM2"
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST \
            "sudo -i bash -c 'cd /home/ubuntu/trading-assistant-backend && pm2 startORReload .pm2/echosystem.config.js'"              
          rm -f private_key.pem
